org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Minecraft Properties
minecraft_version = 26.3-snapshot-8
minecraft_version_supported = [26.3-snapshot-8]
minecraft_version_filter = releases | snapshots
minecraft_version_lower = 26.2
minecraft_version_upper =

# File Name
minecraft_version_name = 26.3
archives_base_name = MoreChiseledBookshelfVariants

## Mod Properties

mod_id=lolmcbv
mod_name=More Chiseled Bookshelf Variants
mod_name_short=More Chiseled Bookshelf Variants
mod_license=CC-BY-NC-SA-4.0
mod_version=1.8.1
mod_group_id=de.pnku.mcbv
mod_description=Adding Chiseled Bookshelf variants to Minecraft

# Quad Properties
quad_version=1.2.0